---
title: "R Notebook"
output: github_document
---

```{r}
library(dada2)
ech = read.table ("SraRunTable(1).csv", header=TRUE, dec=".", stringsAsFactors=TRUE, sep=";")
head (ech)
path <- "/home/rstudio/Dada222/Data"
list.files(path)
```

```{r}
fnFs <- sort(list.files(path, pattern="_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_2.fastq.gz", full.names = TRUE))

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)

plotQualityProfile (fnFs[1:2])

```

```{r}
plotQualityProfile(fnRs[1:2])
```

```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

length(fnFs); length(fnRs)
data.frame(F = basename(fnFs), R = basename(fnRs))
data.frame(F = basename(fnFs), sizeF = file.size(fnFs),
           R = basename(fnRs), sizeR = file.size(fnRs))

```

```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(250,220),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE) 
head(out)
```


```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)
```




